//MapsActions
import {
  SET_USER_LOCATION,
  SET_MAP_LOCATION,
  REQUEST_MERCHANTS,
  LOAD_MERCHANTS
} from "./MapsActions";

export {
  SET_USER_LOCATION,
  SET_MAP_LOCATION,
  REQUEST_MERCHANTS,
  LOAD_MERCHANTS
};

//UserActions
import {
  FILTER_MERCHANTS,
  SET_FILTER,
  SET_ACTIVE_MERCHANT,
  SET_ACTIVE_CARD,
  LOAD_USER,
  REQUEST_USER,
  REQUEST_CARD,
  SET_USER_ID,
  WATCH_USER,
  SET_DEVICE
} from "./UserActions";

export {
  FILTER_MERCHANTS,
  SET_FILTER,
  SET_ACTIVE_MERCHANT,
  SET_ACTIVE_CARD,
  LOAD_USER,
  REQUEST_USER,
  REQUEST_CARD,
  SET_USER_ID,
  WATCH_USER,
  SET_DEVICE
};
