//MapsActions
import {
  SET_USER_LOCATION,
  SET_MAP_LOCATION,
  REQUEST_MERCHANTS
} from "./MapsActions";

export { SET_USER_LOCATION, SET_MAP_LOCATION, REQUEST_MERCHANTS };

//UserActions
import {
  FILTER_MERCHANTS,
  SET_FILTER,
  LOAD_USER,
  REQUEST_USER,
  REQUEST_CARD,
  SET_USER_ID,
  WATCH_USER
} from "./UserActions";

export {
  FILTER_MERCHANTS,
  SET_FILTER,
  LOAD_USER,
  REQUEST_USER,
  REQUEST_CARD,
  SET_USER_ID,
  WATCH_USER
};
